<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="DESKTOP-SE2CFHJ" failures="1" tests="5" name="Default test(failed)" time="0.168" errors="0" timestamp="2022-08-09T15:37:14 IST">
  <testcase classname="Practise.RetryAnalyize" name="modifyContact" time="0.024">
    <skipped/>
  </testcase> <!-- modifyContact -->
  <testcase classname="Practise.RetryAnalyize" name="modifyContact" time="0.003">
    <skipped/>
  </testcase> <!-- modifyContact -->
  <testcase classname="Practise.RetryAnalyize" name="modifyContact" time="0.008">
    <skipped/>
  </testcase> <!-- modifyContact -->
  <testcase classname="Practise.RetryAnalyize" name="modifyContact" time="0.008">
    <skipped/>
  </testcase> <!-- modifyContact -->
  <testcase classname="Practise.RetryAnalyize" name="modifyContact" time="0.007">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at Practise.RetryAnalyize.modifyContact(RetryAnalyize.java:11)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- modifyContact -->
  <testcase classname="Practise.RetryAnalyize" name="createContact" time="0.0">
    <ignored/>
  </testcase> <!-- createContact -->
</testsuite> <!-- Default test(failed) -->
